<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.jpmml</groupId>
		<artifactId>jpmml-parent</artifactId>
		<version>1.0.22</version>
	</parent>

	<groupId>org.jpmml</groupId>
	<artifactId>jpmml-evaluator-parent</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>JPMML-Evaluator-Parent</name>
	<description>A parent Apache Maven Project Object Model (POM) for the JPMML-Evaluator product vertical</description>
	<url>https://github.com/jpmml/jpmml-evaluator-parent</url>

	<licenses>
		<license>
			<name>GNU Affero General Public License (AGPL) version 3.0</name>
			<url>http://www.gnu.org/licenses/agpl-3.0.html</url>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:git@github.com:jpmml/jpmml-evaluator-parent.git</connection>
		<developerConnection>scm:git:git@github.com:jpmml/jpmml-evaluator-parent.git</developerConnection>
		<url>https://github.com/jpmml/jpmml-evaluator-parent</url>
		<tag>HEAD</tag>
	</scm>
	<issueManagement>
		<system>GitHub</system>
		<url>https://github.com/jpmml/jpmml-evaluator-parent/issues</url>
	</issueManagement>

	<properties>
		<guava.version>[19.0, 33.7.2-jre]</guava.version>
		<jcommander.version>2.0</jcommander.version>
		<slf4j.version>2.0.20</slf4j.version>
		<github-release.classifier>executable</github-release.classifier>
		<project.build.outputTimestamp>2026-09-30T19:15:00Z</project.build.outputTimestamp>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.jcommander</groupId>
				<artifactId>jcommander</artifactId>
				<version>${jcommander.version}</version>
			</dependency>

			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>${guava.version}</version>
				<exclusions>
					<exclusion>
						<groupId>com.google.code.findbugs</groupId>
						<artifactId>jsr305</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.google.errorprone</groupId>
						<artifactId>error_prone_annotations</artifactId>
					</exclusion>
					<!--
					<exclusion>
						<groupId>com.google.guava</groupId>
						<artifactId>failureaccess</artifactId>
					</exclusion>
					-->
					<exclusion>
						<groupId>com.google.guava</groupId>
						<artifactId>listenablefuture</artifactId>
					</exclusion>
					<exclusion>
						<groupId>com.google.j2objc</groupId>
						<artifactId>j2objc-annotations</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.checkerframework</groupId>
						<artifactId>*</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>animal-sniffer-annotations</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.jspecify</groupId>
						<artifactId>jspecify</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-bom</artifactId>
				<version>${slf4j.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>de.jutzig</groupId>
					<artifactId>github-release-plugin</artifactId>
					<version>1.2.0</version>
					<executions>
						<execution>
							<id>default-cli</id>
							<configuration>
								<artifact>${project.build.directory}/${project.artifactId}-${github-release.classifier}-${project.version}.${project.packaging}</artifact>
								<description>${project.url}</description>
								<releaseName>${project.version}</releaseName>
								<tag>${project.version}</tag>
							</configuration>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>